### ISSUE TITLE
Missing line in spec.py

### ISSUE THREAD

**Issue by ledragna** [jbloino/estampes#1]
error:
```
Traceback (most recent call last):
  File "/home/marco/.local/bin/esparser", line 33, in <module>
    sys.exit(load_entry_point('estampes', 'console_scripts', 'esparser')())
  File "/home/marco/.local/bin/esparser", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/usr/lib/python3.9/importlib/metadata.py", line 77, in load
    module = import_module(match.group('module'))
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 855, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/marco/git/estampes/progs/esparser.py", line 24, in <module>
    from estampes.base.spectrum import VSPC2DATA, Spectrum
  File "/usr/lib/python3.9/site-packages/shiboken2/files.dir/shibokensupport/__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "/home/marco/git/estampes/estampes/base/spectrum.py", line 21, in <module>
    from estampes.tools.spec import broaden, convert_y
  File "/usr/lib/python3.9/site-packages/shiboken2/files.dir/shibokensupport/__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "/home/marco/git/estampes/estampes/tools/spec.py", line 190
    '/M/cm1': ('M-1.cm-1', '/M/cm', 'dm3.mol-1.cm-1', 'dm3/mol/cm',
IndentationError: unexpected indent
```

Possible solution:
add
`UNIT_EPS = {`
at line 190

**Comment by jbloino** [comment]
Ok, should be fixed in version 0.4.1 (git commit: be2c674ba2260e714585)
